import NavBar from "@/components/NavBar";
import "../globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

import StateProvider from "@/context/StateContext";
export const metadata: Metadata = {
	title: "MBA Ecommerce",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<StateProvider>
				<body className="p-3">
					<header>
						<NavBar />
					</header>
					<main className="main-container">
						<Toaster></Toaster>

						{children}
					</main>
					<footer>
						<Footer />
					</footer>
				</body>
			</StateProvider>
		</html>
	);
}
