import NavBar from "@/components/NavBar";
import "../globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "MBA Ecommerce",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="p-3">
				<header>
					<NavBar />
				</header>
				<main className="main-container">{children}</main>
				<footer>
					<Footer />
				</footer>
			</body>
		</html>
	);
}
